language: node_js
node_js:
  - "7"
  - "6"
cache: yarn
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - COVERAGE=true make tests-single-run
after_success:
  - make coveralls
